FROM jenkins/jenkins:lts-jdk17

# Оставлял на случай если потребуется устанавливать плагины) не пригодилось
RUN jenkins-plugin-cli --plugins pipeline-model-definition github-branch-source:1.8

USER root
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    postgresql-client=15+248* \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
